#
# EXECUTION (from install_yamls repo root):
#
#   make horizon_kuttl
#
# ASSUMPTIONS:
#
# 1. Latest version of kuttl is installed at /usr/local/bin/kubectl-kuttl
# 2. An OCP 4.10+ CRC cluster with Podified Operators has been deployed
# 3. CLI user has access to $KUBECONFIG

apiVersion: kuttl.dev/v1beta1
kind: TestSuite
reportFormat: xml
reportName: kuttl-report-horizon
reportGranularity: test
namespace: horizon-kuttl-tests
timeout: 180
parallel: 1
suppress:
  - events                     # Remove spammy event logs
