# The following CR assumes that a configMap is created starting from
# a local tarball containing the theme
#
# oc create cm horizon-theme --from-file=$HOME/rcue.tar.gz
#
apiVersion: horizon.openstack.org/v1beta1
kind: Horizon
metadata:
  name: horizon
spec:
  replicas: 1
  secret: "osp-secret"
  customServiceConfig: |
    DEBUG = True
    LOGGING['handlers']['console']['level'] = 'DEBUG'
  extraMounts:
    - extraVol:
      - extraVolType: HorizonTheme
        mounts:
        - mountPath: /etc/openstack-dashboard/theme/rcue.tar.gz
          name: horizon-theme
          readOnly: true
          subPath: rcue.tar.gz
        volumes:
        - configMap:
            name: horizon-theme
          name: horizon-theme
