/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group horizon --version v1beta1 --kind Horizon --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
)

// HorizonDefaults -
type HorizonDefaults struct {
	ContainerImageURL string
}

var horizonDefaults HorizonDefaults

// log is for logging in this package.
var horizonlog = logf.Log.WithName("horizon-resource")

// SetupHorizonDefaults - initialize Horizon spec defaults for use with either internal or external webhooks
func SetupHorizonDefaults(defaults HorizonDefaults) {
	horizonDefaults = defaults
	horizonlog.Info("Horizon defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *Horizon) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-horizon-openstack-org-v1beta1-horizon,mutating=true,failurePolicy=fail,sideEffects=None,groups=horizon.openstack.org,resources=horizons,verbs=create;update,versions=v1beta1,name=mhorizon.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &Horizon{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *Horizon) Default() {
	horizonlog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this Horizon spec
func (spec *HorizonSpec) Default() {
    // NOTE: only containerImage validations go here
	if spec.ContainerImage == "" {
		spec.ContainerImage = horizonDefaults.ContainerImageURL
	}
	spec.HorizonSpecCore.Default()
}

// Default - set defaults for this Horizon spec core (this one gets used by OpenstackControlPlane)
func (spec *HorizonSpecCore) Default() {
	// nothing here yet
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-horizon-openstack-org-v1beta1-horizon,mutating=false,failurePolicy=fail,sideEffects=None,groups=horizon.openstack.org,resources=horizons,verbs=create;update,versions=v1beta1,name=vhorizon.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &Horizon{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Horizon) ValidateCreate() (admission.Warnings, error) {
	horizonlog.Info("validate create", "name", r.Name)

	var allErrs field.ErrorList
	basePath := field.NewPath("spec")

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, r.Spec.ValidateTopology(basePath, r.Namespace)...)

	if len(allErrs) != 0 {
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "horizon.openstack.org", Kind: "Horizon"},
			r.Name, allErrs)
	}
	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *Horizon) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	horizonlog.Info("validate update", "name", r.Name)

	var allErrs field.ErrorList
	basePath := field.NewPath("spec")

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, r.Spec.ValidateTopology(basePath, r.Namespace)...)

	if len(allErrs) != 0 {
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "horizon.openstack.org", Kind: "Horizon"},
			r.Name, allErrs)
	}
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *Horizon) ValidateDelete() (admission.Warnings, error) {
	horizonlog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
